# This docker-compose file can be used to bring up an example instance of oauth2-proxy
# for manual testing and exploration of features.
# Alongside OAuth2-Proxy, this file also starts Keycloak to act as the identity provider,
# HTTPBin as an example upstream.
#
# This can either be created using docker-compose
#    docker-compose -f docker-compose-keycloak.yaml <command>
# Or:
#    make keycloak-<command> (eg. make keycloak-up, make keycloak-down)
#
# Access http://oauth2-proxy.localtest.me:4180 to initiate a login cycle using user=admin@example.com, password=password
# Access http://keycloak.localtest.me:9080 with the same credentials to check out the settings
services:
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.8.1
    command: --config /oauth2-proxy.cfg
    hostname: oauth2-proxy
    volumes:
      - "./oauth2-proxy/config/oauth2-proxy.cfg:/oauth2-proxy.cfg"
    environment:
      OAUTH2_PROXY_SKIP_AUTH_ROUTES: "GET=^/actuator.*${INFRASTACK_OAUTH2_PROXY_SKIP_AUTH_ROUTES_ADD:+,}${INFRASTACK_OAUTH2_PROXY_SKIP_AUTH_ROUTES_ADD-}"
      OAUTH2_PROXY_API_ROUTES: ${INFRASTACK_OAUTH2_PROXY_API_ROUTES-^/.*}
    restart: unless-stopped
    ports:
      - 4180:4180/tcp
    networks:
      keycloak: {}
      oauth2-proxy: {}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      keycloak:
        condition: service_healthy

  keycloak:
    container_name: keycloak
    image: keycloak/keycloak:26.1
    hostname: keycloak
    command:
      - 'start-dev'
      - '--http-port=9080'
      - '--import-realm'
    volumes:
      - ./keycloak/data:/opt/keycloak/data/import
      - ./keycloak/health-check.sh:/opt/keycloak/health-check.sh
    environment:
      KC_HTTP_PORT: 9080
      KEYCLOAK_ADMIN: admin@example.com
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_BOOTSTRAP_ADMIN_USERNAME: admin@example.com
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
      KC_HEALTH_ENABLED: true
    ports:
      - 9080:9080/tcp
    networks:
      keycloak:
        aliases:
          - keycloak.localtest.me
    healthcheck:
      test: [
        "CMD-SHELL",
        "bash /opt/keycloak/health-check.sh"
      ]
      interval: 15s
      timeout: 10s
      retries: 12

networks:
  keycloak: {}
  oauth2-proxy: {}
